version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install
      - cd frontend && npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - frontend/public/*
    - frontend/public/**/*
    - frontend/node_modules/*
    - frontend/node_modules/**/*
    - node_modules/*
    - node_modules/**/*
    - frontend/build/**/*
    - frontend/build/*
    - ./*.js
    - package.json
    - ./*/package.json
